# Generated by Django 2.1.2 on 2018-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('marketcap', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('sector', models.CharField(blank=True, default='', max_length=100)),
                ('industry', models.CharField(blank=True, default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
