# Generated by Django 2.1.2 on 2018-10-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='marketcap',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
    ]
